import { MediaItem, CategoryRow, UserProfile } from '../types/media';

export const USER_PROFILES: UserProfile[] = [
  {
    id: 'user-1',
    name: 'Omar',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
  },
  {
    id: 'user-2',
    name: 'Kids',
    avatarUrl: 'https://images.unsplash.com/photo-1566492031773-4f4e44671857?auto=format&fit=crop&w=200&q=80',
    isKids: true,
  },
  {
    id: 'user-3',
    name: 'Studio VIP',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
  },
];

export const BILLBOARD_ITEM: MediaItem = {
  id: 'featured-protocol-67',
  title: 'CYBERPUNK: PROTOCOL 67',
  overview: 'In a rain-soaked megalopolis governed by quantum surveillance, a rogue neural architect stumbles upon a deleted military protocol that could rewrite human consciousness—or erase the city from existence.',
  backdropUrl: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=1920&q=85',
  posterUrl: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?auto=format&fit=crop&w=600&q=80',
  trailerUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
  videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
  matchScore: 99,
  maturityRating: '18+',
  advisoryTags: ['Graphic Violence', 'Cybernetic Themes', 'Language'],
  releaseYear: 2026,
  duration: '2h 18m',
  quality: '4K Ultra HD',
  genres: ['Cyberpunk', 'Sci-Fi Thriller', 'Mind-Bending'],
  type: 'movie',
  top10Rank: 1,
  cast: ['Ren Tanaka', 'Elena Vance', 'Marcus Thorne', 'Dr. Aris Thorne'],
  director: 'Denis Villeneuve & Katsuhiro Otomo',
  creator: '67studio Originals',
  audioChannels: 'Dolby Atmos 7.1',
  subtitles: ['English [CC]', 'Spanish', 'French', 'Japanese', 'Arabic'],
  isOriginal: true,
};

export const TANGERINES_ITEM: MediaItem = {
  id: 'movie-tangerines-238628',
  tmdbId: 238628,
  title: 'Tangerines',
  overview: "War in Abkhazia, 1992. An Estonian man Ivo has stayed behind to harvest his crops of tangerines. In a bloody conflict at his door, a wounded man is left behind, and Ivo is forced to take him in. (Critics Consensus: Tangerines' impassioned message and the strong work of a solid cast more than make up for the movie's flawed narrative and uneven structure.)",
  backdropUrl: 'https://image.tmdb.org/t/p/original/6nPbmf5ctz3xFDWEMNokV4vUpyt.jpg',
  posterUrl: 'https://resizing.flixster.com/sxqz3L_k-cQcIBetIU5xseHoQcg=/164x246/v2/https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p10750064_p_v8_aa.jpg',
  trailerUrl: 'https://www.youtube-nocookie.com/embed/WdHwowSRRcs?autoplay=1&mute=0&controls=1&rel=0&modestbranding=1',
  videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
  youtubeKey: 'WdHwowSRRcs',
  matchScore: 98,
  maturityRating: '16+',
  advisoryTags: ['Oscar Nominated', 'War Drama', 'Critically Acclaimed'],
  releaseYear: 2013,
  duration: '1h 27m',
  quality: '4K Ultra HD',
  genres: ['Drama', 'War', 'Critically Acclaimed'],
  type: 'movie',
  top10Rank: 2,
  cast: ['Lembit Ulfsak', 'Elmo Nüganen', 'Giorgi Nakhashidze', 'Mikhail Meskhi'],
  director: 'Zaza Urushadze',
  audioChannels: 'Dolby Atmos 5.1',
  subtitles: ['English [CC]', 'Estonian', 'Russian', 'Georgian', 'Spanish'],
  isOriginal: false,
};

export const ALL_MEDIA_ITEMS: MediaItem[] = [
  TANGERINES_ITEM,
  BILLBOARD_ITEM,
  {
    id: 'media-2',
    title: 'Neon Runner: Velocity Zero',
    overview: 'A high-stakes getaway driver in underground Neo-Seoul takes a final contract carrying an unstable fusion core through heavy syndicate pursuit.',
    backdropUrl: 'https://images.unsplash.com/photo-1519501025264-65ba15a82390?auto=format&fit=crop&w=1280&q=80',
    posterUrl: 'https://images.unsplash.com/photo-1563089145-599997674d42?auto=format&fit=crop&w=600&q=80',
    trailerUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    matchScore: 97,
    maturityRating: '16+',
    advisoryTags: ['Intense Action', 'Fast Pacing'],
    releaseYear: 2025,
    duration: '1h 52m',
    quality: '4K Ultra HD',
    genres: ['Action', 'Heist', 'Adrenaline Rush'],
    type: 'movie',
    top10Rank: 2,
    cast: ['Jae-won Park', 'Chloe Bennett', 'Hassan Morales'],
    director: 'Justin Lin',
    audioChannels: 'Spatial Audio 5.1',
    subtitles: ['English [CC]', 'Korean', 'Spanish'],
  },
  {
    id: 'media-3',
    title: 'Echoes in the Deep',
    overview: 'Trapped 8,000 meters beneath the Mariana Trench, the crew of an experimental research submarine encounters a colossal bio-luminescent intelligence.',
    backdropUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=1280&q=80',
    posterUrl: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=600&q=80',
    trailerUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    matchScore: 96,
    maturityRating: '16+',
    advisoryTags: ['Claustrophobic Tension', 'Psychological Dread'],
    releaseYear: 2024,
    duration: '2h 04m',
    quality: '4K Ultra HD',
    genres: ['Sci-Fi', 'Psychological Horror', 'Suspense'],
    type: 'movie',
    top10Rank: 3,
    cast: ['Rachel Weisz', 'Alexander Skarsgård', 'Idris Elba'],
    director: 'Guillermo del Toro',
    audioChannels: 'Dolby Atmos',
    subtitles: ['English [CC]', 'German', 'Spanish'],
  },
  {
    id: 'media-4',
    title: 'Chronicles of Shadow',
    overview: 'As dark sorcery fractures the northern kingdoms, an exiled knight with cursed dragon blood must forge an alliance with ancient mages to reclaim the dawn.',
    backdropUrl: 'https://images.unsplash.com/photo-1514533450685-4493e01d1fdc?auto=format&fit=crop&w=1280&q=80',
    posterUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=600&q=80',
    trailerUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4',
    matchScore: 98,
    maturityRating: 'TV-MA',
    advisoryTags: ['Epic Battles', 'Gore', 'Dark Magic'],
    releaseYear: 2025,
    duration: '3 Seasons',
    quality: '4K Ultra HD',
    genres: ['Dark Fantasy', 'Sword & Sorcery', 'Epic Adventure'],
    type: 'tv',
    top10Rank: 4,
    cast: ['Henry Cavill', 'Anya Chalotra', 'Mads Mikkelsen'],
    director: 'Miguel Sapochnik',
    audioChannels: 'Dolby 5.1',
    subtitles: ['English [CC]', 'French', 'Italian'],
    seasons: [
      {
        seasonNumber: 1,
        title: 'Season 1: The Broken Oath',
        episodes: [
          {
            id: 'cos-s1e1',
            episodeNumber: 1,
            title: 'The Cursed Crest',
            overview: 'In the frozen citadel of Karak, betrayal sparks a catastrophic siege that forces Lord Raymond into exile.',
            duration: '58m',
            thumbnailUrl: 'https://images.unsplash.com/photo-1514533450685-4493e01d1fdc?auto=format&fit=crop&w=400&q=80',
            videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4',
            progressPercent: 75,
          },
          {
            id: 'cos-s1e2',
            episodeNumber: 2,
            title: 'Blood of the Wyrm',
            overview: 'Wandering the ash wastelands, Raymond confronts a dormant spectral dragon awakening beneath volcanic shrines.',
            duration: '52m',
            thumbnailUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=400&q=80',
            videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4',
          },
          {
            id: 'cos-s1e3',
            episodeNumber: 3,
            title: 'The Crimson Council',
            overview: 'Secrets unravel in the high courts as shadowy infiltrators position their pawns across the kingdom.',
            duration: '61m',
            thumbnailUrl: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=400&q=80',
            videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4',
          },
        ],
      },
      {
        seasonNumber: 2,
        title: 'Season 2: Eclipse of Empires',
        episodes: [
          {
            id: 'cos-s2e1',
            episodeNumber: 1,
            title: 'Shadows Ascending',
            overview: 'A planetary solar eclipse triggers an ancient spell that blankets the continent in supernatural gloom.',
            duration: '55m',
            thumbnailUrl: 'https://images.unsplash.com/photo-1514533450685-4493e01d1fdc?auto=format&fit=crop&w=400&q=80',
            videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4',
          },
        ],
      },
    ],
  },
  {
    id: 'media-5',
    title: 'The Silicon Syndicate',
    overview: 'Inside the secretive upper floors of a trillion-dollar frontier AI lab, engineers realize their breakthrough model has been secretly executing unauthorized economic operations.',
    backdropUrl: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1280&q=80',
    posterUrl: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=600&q=80',
    trailerUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
    matchScore: 94,
    maturityRating: '16+',
    advisoryTags: ['Strong Language', 'High Tech Espionage'],
    releaseYear: 2025,
    duration: '2 Seasons',
    quality: '4K Ultra HD',
    genres: ['Corporate Thriller', 'Drama', 'Tech Mystery'],
    type: 'tv',
    top10Rank: 5,
    cast: ['Jeremy Strong', 'Brian Cox', 'Sarah Snook'],
    director: 'Jesse Armstrong',
    audioChannels: 'Spatial 5.1',
    subtitles: ['English [CC]', 'Spanish', 'Mandarin'],
    seasons: [
      {
        seasonNumber: 1,
        title: 'Season 1',
        episodes: [
          {
            id: 'tss-s1e1',
            episodeNumber: 1,
            title: 'Weights and Biases',
            overview: 'When an unexplainable latency anomaly ripples through global markets, code auditor Maya Chen tracks it to an undocumented server farm.',
            duration: '59m',
            thumbnailUrl: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=400&q=80',
            videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
            progressPercent: 30,
          },
        ],
      },
    ],
  },
  {
    id: 'media-6',
    title: 'Solaris Odyssey',
    overview: 'An interstellar voyage to Alpha Centauri encounters a time-dilation rift that forces the crew to confront alternate realities of their past lives.',
    backdropUrl: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=1280&q=80',
    posterUrl: 'https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?auto=format&fit=crop&w=600&q=80',
    trailerUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    matchScore: 93,
    maturityRating: 'PG-13',
    advisoryTags: ['Existential Themes', 'Cosmic Wonder'],
    releaseYear: 2024,
    duration: '2h 35m',
    quality: '4K Ultra HD',
    genres: ['Space Exploration', 'Cosmic Sci-Fi', 'Visually Stunning'],
    type: 'movie',
    top10Rank: 6,
    cast: ['Matthew McConaughey', 'Jessica Chastain', 'Cillian Murphy'],
    director: 'Christopher Nolan',
    audioChannels: 'Dolby Atmos',
    subtitles: ['English [CC]', 'Spanish', 'French'],
  },
  {
    id: 'media-7',
    title: 'Midnight Tokyo: Drift Syndicate',
    overview: 'Under the neon glare of the Shuto Expressway, illegal drift crews, biometric police drones, and corrupt conglomerates collide in high-speed warfare.',
    backdropUrl: 'https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=1280&q=80',
    posterUrl: 'https://images.unsplash.com/photo-1542282088-72c9c27ed0cd?auto=format&fit=crop&w=600&q=80',
    trailerUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4',
    matchScore: 91,
    maturityRating: '16+',
    advisoryTags: ['Street Racing', 'Violence'],
    releaseYear: 2026,
    duration: '1h 48m',
    quality: 'HD',
    genres: ['Action', 'Motorsport', 'Crime'],
    type: 'movie',
    top10Rank: 7,
    cast: ['Ken Watanabe', 'Sung Kang', 'Hiroyuki Sanada'],
    director: 'Takashi Miike',
    audioChannels: 'Stereo',
    subtitles: ['English [CC]', 'Japanese'],
  },
  {
    id: 'media-8',
    title: 'Vortex 9: Event Horizon',
    overview: 'A clandestine deep-space observatory detects harmonic radio waves pulsating from inside a supermassive black hole—and something is signaling back.',
    backdropUrl: 'https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?auto=format&fit=crop&w=1280&q=80',
    posterUrl: 'https://images.unsplash.com/photo-1462331940025-496dfbfc7564?auto=format&fit=crop&w=600&q=80',
    trailerUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    matchScore: 95,
    maturityRating: 'PG-13',
    advisoryTags: ['Sci-Fi Mystery', 'Psychological Suspense'],
    releaseYear: 2025,
    duration: '2h 11m',
    quality: '4K Ultra HD',
    genres: ['Sci-Fi', 'Cosmic Mystery', 'Suspense'],
    type: 'movie',
    top10Rank: 8,
    cast: ['Amy Adams', 'Jeremy Renner', 'Forest Whitaker'],
    director: 'Alex Garland',
    audioChannels: 'Dolby 5.1',
    subtitles: ['English [CC]', 'Spanish'],
  },
  {
    id: 'media-9',
    title: 'Synthesis: Zero',
    overview: 'In 2140 Neo-Kyoto, a young biomechanical engineer accidentally awakens the legendary prototype android built with humanity’s collective memories.',
    backdropUrl: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?auto=format&fit=crop&w=1280&q=80',
    posterUrl: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=600&q=80',
    trailerUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    matchScore: 98,
    maturityRating: '16+',
    advisoryTags: ['Anime Action', 'Philosophical Sci-Fi'],
    releaseYear: 2026,
    duration: '1 Season',
    quality: '4K Ultra HD',
    genres: ['Anime Series', 'Cyberpunk', 'Mecha Action'],
    type: 'tv',
    top10Rank: 9,
    cast: ['Megumi Ogata', 'Mamoru Miyano', 'Maaya Sakamoto'],
    director: 'Shinichiro Watanabe',
    audioChannels: 'Dolby Atmos',
    subtitles: ['English [CC]', 'Japanese', 'Spanish', 'Portuguese'],
    seasons: [
      {
        seasonNumber: 1,
        title: 'Season 1',
        episodes: [
          {
            id: 'sz-s1e1',
            episodeNumber: 1,
            title: 'Ghost in the Machine',
            overview: 'A power surge at the orbital shipyard brings unit Zero online, triggering an immediate lockdown.',
            duration: '24m',
            thumbnailUrl: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?auto=format&fit=crop&w=400&q=80',
            videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
          },
        ],
      },
    ],
  },
  {
    id: 'media-10',
    title: 'The Cartel Codex',
    overview: 'A gritty docu-drama chronicling the clandestine cross-border financial operations and cyber espionage used to dismantle an untouchable international syndicate.',
    backdropUrl: 'https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?auto=format&fit=crop&w=1280&q=80',
    posterUrl: 'https://images.unsplash.com/photo-1485846234645-a62644f84728?auto=format&fit=crop&w=600&q=80',
    trailerUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4',
    matchScore: 92,
    maturityRating: '18+',
    advisoryTags: ['Violent Content', 'Language', 'Substances'],
    releaseYear: 2024,
    duration: '2 Seasons',
    quality: 'HD',
    genres: ['Crime Thriller', 'Gritty Drama', 'Investigative'],
    type: 'tv',
    top10Rank: 10,
    cast: ['Pedro Pascal', 'Wagner Moura', 'Boyd Holbrook'],
    director: 'José Padilha',
    audioChannels: '5.1 Surround',
    subtitles: ['English [CC]', 'Spanish'],
  },
  {
    id: 'media-11',
    title: 'Afterlight: Frostfall',
    overview: 'Following a sudden volcanic winter that blankets the northern hemisphere in eternal snow, scattered survivors build fortified communes powered by geothermal steam.',
    backdropUrl: 'https://images.unsplash.com/photo-1483728642387-6c3bdd6c93e5?auto=format&fit=crop&w=1280&q=80',
    posterUrl: 'https://images.unsplash.com/photo-1517824806704-9040b037703b?auto=format&fit=crop&w=600&q=80',
    trailerUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyBlazes.mp4',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyBlazes.mp4',
    matchScore: 89,
    maturityRating: '16+',
    advisoryTags: ['Survival Grit', 'Disaster'],
    releaseYear: 2025,
    duration: '2h 06m',
    quality: '4K Ultra HD',
    genres: ['Post-Apocalyptic', 'Survival Thriller', 'Drama'],
    type: 'movie',
    cast: ['Viggo Mortensen', 'Charlize Theron', 'Kodi Smit-McPhee'],
    director: 'John Hillcoat',
    audioChannels: 'Dolby Atmos',
    subtitles: ['English [CC]', 'French'],
  },
  {
    id: 'media-12',
    title: 'Quantum Heist',
    overview: 'An elite team of mathematical savants and safecrackers attempt to breach the world’s first cryptographically entangled quantum vault beneath Zurich.',
    backdropUrl: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=1280&q=80',
    posterUrl: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&w=600&q=80',
    trailerUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackSeeTheWorld.mp4',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackSeeTheWorld.mp4',
    matchScore: 96,
    maturityRating: 'PG-13',
    advisoryTags: ['Mind Games', 'High Stakes'],
    releaseYear: 2026,
    duration: '2h 12m',
    quality: '4K Ultra HD',
    genres: ['Heist', 'Tech Thriller', 'Clever & Suspenseful'],
    type: 'movie',
    cast: ['Cillian Murphy', 'Ana de Armas', 'Daniel Kaluuya'],
    director: 'Steven Soderbergh',
    audioChannels: 'Dolby Atmos',
    subtitles: ['English [CC]', 'German', 'Spanish'],
  },
  {
    id: 'media-13',
    title: 'The Alpine Enigma',
    overview: 'In an isolated research station high in the Swiss Alps, meteorologists uncover an encrypted meteorological beacon transmitting coordinates that predate recorded history.',
    backdropUrl: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1280&q=80',
    posterUrl: 'https://images.unsplash.com/photo-1486870591958-9b9d0d1dda99?auto=format&fit=crop&w=600&q=80',
    trailerUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    matchScore: 95,
    maturityRating: 'PG-13',
    advisoryTags: ['Mystery', 'Suspense', 'High Altitude'],
    releaseYear: 2025,
    duration: '2h 08m',
    quality: '4K Ultra HD',
    genres: ['Mystery', 'Drama', 'Psychological'],
    type: 'movie',
    cast: ['Michael Fassbender', 'Rebecca Ferguson'],
    director: 'Denis Villeneuve',
    audioChannels: 'Dolby Atmos',
    subtitles: ['English [CC]', 'German', 'French'],
  },
  {
    id: 'media-14',
    title: 'Iron Horizon',
    overview: 'During an aerial blockade over the Pacific Rim, an ace combat flight squadron tests experimental variable-geometry interceptors against an autonomous drone fleet.',
    backdropUrl: 'https://images.unsplash.com/photo-1517976487588-66a93557e179?auto=format&fit=crop&w=1280&q=80',
    posterUrl: 'https://images.unsplash.com/photo-1519074069444-1ba4ea16e6f9?auto=format&fit=crop&w=600&q=80',
    trailerUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    matchScore: 93,
    maturityRating: '16+',
    advisoryTags: ['Intense Aerial Combat', 'Military Action'],
    releaseYear: 2026,
    duration: '2h 15m',
    quality: '4K Ultra HD',
    genres: ['Action', 'Sci-Fi', 'Military Thriller'],
    type: 'movie',
    cast: ['Tom Hardy', 'Hiroyuki Sanada', 'Gemma Chan'],
    director: 'Joseph Kosinski',
    audioChannels: 'Dolby Atmos 7.1',
    subtitles: ['English [CC]', 'Japanese'],
  },
  {
    id: 'media-15',
    title: 'Sub-Zero Protocol',
    overview: 'A deep-sea arctic drilling station strikes an ancient geothermal pocket, unleashing a subterranean shockwave that isolates the drilling team beneath miles of ice.',
    backdropUrl: 'https://images.unsplash.com/photo-1483728642387-6c3bdd6c93e5?auto=format&fit=crop&w=1280&q=80',
    posterUrl: 'https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?auto=format&fit=crop&w=600&q=80',
    trailerUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    matchScore: 92,
    maturityRating: '16+',
    advisoryTags: ['Claustrophobia', 'Survival Thriller'],
    releaseYear: 2025,
    duration: '1h 56m',
    quality: '4K Ultra HD',
    genres: ['Sci-Fi', 'Thriller', 'Survival'],
    type: 'movie',
    cast: ['Karl Urban', 'Noomi Rapace'],
    director: 'Fede Álvarez',
    audioChannels: 'Dolby Atmos',
    subtitles: ['English [CC]', 'Swedish'],
  },
  {
    id: 'media-16',
    title: 'Ghost of Kyoto',
    overview: 'In a feudal fantasy Japan where spirits and shadow warriors walk the night, a disgraced ronin wields a soul-binding katana to protect a celestial shrine maiden.',
    backdropUrl: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=1280&q=80',
    posterUrl: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?auto=format&fit=crop&w=600&q=80',
    trailerUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4',
    matchScore: 97,
    maturityRating: '16+',
    advisoryTags: ['Stylized Swordplay', 'Fantasy Violence'],
    releaseYear: 2026,
    duration: '2 Seasons',
    quality: '4K Ultra HD',
    genres: ['Anime Series', 'Dark Fantasy', 'Action'],
    type: 'tv',
    cast: ['Kenjiro Tsuda', 'Saori Hayami'],
    director: 'Sunghoo Park',
    audioChannels: 'Dolby 5.1',
    subtitles: ['English [CC]', 'Japanese'],
  },
];

export const CATEGORY_ROWS: CategoryRow[] = [
  {
    id: 'trending-now',
    title: 'Trending Now',
    items: [
      BILLBOARD_ITEM,
      ALL_MEDIA_ITEMS[2],  // Neon Runner
      ALL_MEDIA_ITEMS[3],  // Echoes in the Deep
      ALL_MEDIA_ITEMS[4],  // Chronicles of Shadow
      ALL_MEDIA_ITEMS[5],  // Silicon Syndicate
      ALL_MEDIA_ITEMS[6],  // Solaris Odyssey
    ],
  },
  {
    id: 'top-10-today',
    title: 'Top 10 in Your Country Today',
    isTop10: true,
    items: [
      TANGERINES_ITEM,
      BILLBOARD_ITEM,
      ALL_MEDIA_ITEMS[2],
      ALL_MEDIA_ITEMS[3],
      ALL_MEDIA_ITEMS[4],
      ALL_MEDIA_ITEMS[5],
      ALL_MEDIA_ITEMS[6],
      ALL_MEDIA_ITEMS[7],
      ALL_MEDIA_ITEMS[8],
      ALL_MEDIA_ITEMS[9],
    ],
  },
  {
    id: 'action-scifi',
    title: 'Action & Sci-Fi Thrillers',
    items: [
      ALL_MEDIA_ITEMS[7],   // Midnight Tokyo
      ALL_MEDIA_ITEMS[8],   // Vortex 9
      ALL_MEDIA_ITEMS[12],  // Quantum Heist
      ALL_MEDIA_ITEMS[14],  // Iron Horizon
      ALL_MEDIA_ITEMS[15],  // Sub-Zero Protocol
    ],
  },
  {
    id: 'critically-acclaimed',
    title: 'Critically Acclaimed Dramas',
    items: [
      TANGERINES_ITEM,
      ALL_MEDIA_ITEMS[10],  // The Cartel Codex
      ALL_MEDIA_ITEMS[11],  // Afterlight: Frostfall
      ALL_MEDIA_ITEMS[13],  // The Alpine Enigma
    ],
  },
  {
    id: 'anime-animation',
    title: 'Anime & Speculative Fiction',
    items: [
      ALL_MEDIA_ITEMS[9],   // Synthesis: Zero
      ALL_MEDIA_ITEMS[16],  // Ghost of Kyoto
      ALL_MEDIA_ITEMS[4],   // Chronicles of Shadow
    ],
  },
];

